# Generated by Django 5.2.5 on 2025-10-03 01:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliaDenuncia',
            fields=[
                ('id_familia_denuncia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_familia_denuncia', models.CharField(max_length=100, unique=True)),
                ('codigo_familia', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Familia de Denuncia',
                'verbose_name_plural': 'Familias de Denuncia',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='ServiciosEmergencia',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=100, unique=True)),
                ('codigo_servicio', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Servicio de Emergencia',
                'verbose_name_plural': 'Servicios de Emergencia',
            },
        ),
        migrations.CreateModel(
            name='TiposVehiculos',
            fields=[
                ('id_tipo_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_vehiculo', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Vehículo',
                'verbose_name_plural': 'Tipos de Vehículos',
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_turno', models.CharField(max_length=50, unique=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.CreateModel(
            name='GrupoDenuncia',
            fields=[
                ('id_grupo_denuncia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grupo_denuncia', models.CharField(max_length=100)),
                ('codigo_grupo', models.CharField(max_length=10)),
                ('id_familia_denuncia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Seguridad.familiadenuncia')),
            ],
            options={
                'verbose_name': 'Grupo de Denuncia',
                'verbose_name_plural': 'Grupos de Denuncia',
                'unique_together': {('id_familia_denuncia', 'codigo_grupo')},
            },
        ),
        migrations.CreateModel(
            name='SubgrupoDenuncia',
            fields=[
                ('id_subgrupo_denuncia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_subgrupo_denuncia', models.CharField(max_length=100)),
                ('codigo_subgrupo', models.CharField(max_length=10)),
                ('id_grupo_denuncia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Seguridad.grupodenuncia')),
            ],
            options={
                'verbose_name': 'Subgrupo de Denuncia',
                'verbose_name_plural': 'Subgrupos de Denuncia',
                'unique_together': {('id_grupo_denuncia', 'codigo_subgrupo')},
            },
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id_requerimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_requerimiento', models.CharField(max_length=200)),
                ('codigo_requerimiento', models.CharField(max_length=10)),
                ('clasificacion_requerimiento', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=10)),
                ('descripcion_requerimiento', models.TextField()),
                ('id_subgrupo_denuncia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Seguridad.subgrupodenuncia')),
            ],
            options={
                'verbose_name': 'Requerimiento',
                'verbose_name_plural': 'Requerimientos',
                'unique_together': {('id_subgrupo_denuncia', 'codigo_requerimiento')},
            },
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('patente_vehiculo', models.CharField(max_length=10, unique=True)),
                ('marca_vehiculo', models.CharField(max_length=50)),
                ('modelo_vehiculo', models.CharField(max_length=50)),
                ('codigo_vehiculo', models.CharField(max_length=10)),
                ('estado_vehiculo', models.CharField(choices=[('Disponible', 'Disponible'), ('En mantención', 'En mantención'), ('Asignado', 'Asignado'), ('Inactivo', 'Inactivo')], default='Disponible', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Seguridad.tiposvehiculos')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
        migrations.CreateModel(
            name='VillasCuadrantes',
            fields=[
                ('id_villa_cuadrante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_villa', models.CharField(max_length=100)),
                ('cuadrante', models.CharField(max_length=10)),
                ('direccion_referencia', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Villa y Cuadrante',
                'verbose_name_plural': 'Villas y Cuadrantes',
                'unique_together': {('nombre_villa', 'cuadrante')},
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id_denuncia', models.AutoField(primary_key=True, serialize=False)),
                ('hora_denuncia', models.DateTimeField()),
                ('fecha_denuncia', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
                ('detalle_denuncia', models.TextField()),
                ('visibilidad_camaras_denuncia', models.BooleanField(default=False)),
                ('hora_llegada_movil', models.DateTimeField(blank=True, null=True)),
                ('labor_realizada_denuncia', models.TextField()),
                ('termino_evento', models.DateTimeField(blank=True, null=True)),
                ('tiempo_total_procedimiento_minutos', models.IntegerField(blank=True, null=True)),
                ('estado_denuncia', models.CharField(choices=[('Recibido', 'Recibido'), ('En proceso', 'En proceso'), ('Completado', 'Completado')], default='Recibido', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Seguridad.requerimiento')),
                ('id_turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Seguridad.turnos')),
                ('id_villa_cuadrante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Seguridad.villascuadrantes')),
            ],
            options={
                'verbose_name': 'Denuncia',
                'verbose_name_plural': 'Denuncias',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('rut_usuario', models.CharField(help_text='Formato: 12345678-9', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe tener el formato: 12345678-9', regex='^\\d{7,8}-[\\dkK]$')])),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('apellido_pat_usuario', models.CharField(max_length=100)),
                ('apellido_mat_usuario', models.CharField(max_length=100)),
                ('correo_electronico_usuario', models.EmailField(max_length=254, unique=True)),
                ('telefono_movil_usuario', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener formato: +56912345678', regex='^\\+?56?9?\\d{8}$')])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Seguridad.roles')),
                ('id_turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Seguridad.turnos')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='DerivacionesDenuncia',
            fields=[
                ('id_derivacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_derivacion', models.CharField(choices=[('Primaria', 'Derivación Primaria'), ('Adicional', 'Derivación Adicional')], default='Primaria', max_length=20)),
                ('hora_derivacion', models.DateTimeField()),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('id_denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seguridad.denuncia')),
                ('id_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Seguridad.serviciosemergencia')),
                ('id_conductor', models.ForeignKey(blank=True, limit_choices_to={'id_rol__nombre_rol__in': ['Conductor', 'Inspector']}, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Derivación de Denuncia',
                'verbose_name_plural': 'Derivaciones de Denuncias',
            },
        ),
        migrations.AddField(
            model_name='denuncia',
            name='id_operador1',
            field=models.ForeignKey(limit_choices_to={'id_rol__nombre_rol': 'Operador'}, on_delete=django.db.models.deletion.PROTECT, related_name='denuncias_operador1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='id_operador2',
            field=models.ForeignKey(blank=True, limit_choices_to={'id_rol__nombre_rol': 'Operador'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='denuncias_operador2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='id_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denuncias_solicitante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MovilesDenuncia',
            fields=[
                ('id_movil_denuncia', models.AutoField(primary_key=True, serialize=False)),
                ('orden_asignacion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('hora_asignacion', models.DateTimeField()),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('id_denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seguridad.denuncia')),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Seguridad.vehiculos')),
                ('id_conductor', models.ForeignKey(limit_choices_to={'id_rol__nombre_rol__in': ['Conductor', 'Inspector']}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Móvil en Denuncia',
                'verbose_name_plural': 'Móviles en Denuncias',
                'unique_together': {('id_denuncia', 'orden_asignacion')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionesVehiculos',
            fields=[
                ('id_asignacion_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Seguridad.turnos')),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Seguridad.vehiculos')),
                ('id_conductor', models.ForeignKey(limit_choices_to={'id_rol__nombre_rol__in': ['Conductor', 'Inspector']}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de Vehículo',
                'verbose_name_plural': 'Asignaciones de Vehículos',
                'unique_together': {('id_conductor', 'id_vehiculo', 'fecha_asignacion')},
            },
        ),
    ]
