# Generated by Django 5.2.7 on 2025-10-27 07:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Seguridad', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudadano',
            fields=[
                ('id_ciudadano', models.AutoField(primary_key=True, serialize=False)),
                ('rut_ciudadano', models.CharField(max_length=10, unique=True)),
                ('nombre_ciudadano', models.CharField(max_length=100)),
                ('apellido_pat_ciudadano', models.CharField(max_length=225)),
                ('apellido_mat_ciudadano', models.CharField(max_length=100)),
                ('correo_electronico_ciudadano', models.CharField(max_length=100, unique=True)),
                ('telefono_movil_ciudadano', models.CharField(max_length=13)),
                ('fecha_creacion_ciudadano', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion_ciudadano', models.DateTimeField(auto_now=True)),
                ('contraseña_ciudadano', models.CharField(max_length=225)),
                ('ultimo_inicio_ciudadano', models.DateTimeField(blank=True, null=True)),
                ('is_active_ciudadano', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ciudadano',
                'verbose_name_plural': 'Ciudadanos',
                'db_table': 'Seguridad_ciudadano',
            },
        ),
        migrations.CreateModel(
            name='FamiliaDenuncia',
            fields=[
                ('id_familia_denuncia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_familia_denuncia', models.CharField(max_length=100, unique=True)),
                ('codigo_familia', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Familia de Denuncia',
                'verbose_name_plural': 'Familias de Denuncia',
                'db_table': 'Seguridad_familiadenuncia',
            },
        ),
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id_radio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_radio', models.CharField(max_length=50, unique=True)),
                ('codigo_radio', models.CharField(max_length=20, unique=True)),
                ('descripcion_radio', models.TextField()),
                ('estado_radio', models.CharField(max_length=20)),
                ('fecha_creacion_radio', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Radio',
                'verbose_name_plural': 'Radios',
                'db_table': 'Seguridad_radio',
            },
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id_requerimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_requerimiento', models.CharField(max_length=200)),
                ('codigo_requerimiento', models.CharField(max_length=10)),
                ('clasificacion_requerimiento', models.CharField(max_length=10)),
                ('descripcion_requerimiento', models.TextField()),
            ],
            options={
                'verbose_name': 'Requerimiento',
                'verbose_name_plural': 'Requerimientos',
                'db_table': 'Seguridad_requerimiento',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'Seguridad_roles',
            },
        ),
        migrations.CreateModel(
            name='ServiciosEmergencia',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=100, unique=True)),
                ('codigo_servicio', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Servicio de Emergencia',
                'verbose_name_plural': 'Servicios de Emergencia',
                'db_table': 'Seguridad_serviciosemergencia',
            },
        ),
        migrations.CreateModel(
            name='TiposVehiculos',
            fields=[
                ('id_tipo_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_vehiculo', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Vehículo',
                'verbose_name_plural': 'Tipos de Vehículos',
                'db_table': 'Seguridad_tiposvehiculos',
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_turno', models.CharField(max_length=50, unique=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'db_table': 'Seguridad_turnos',
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id_denuncia', models.AutoField(primary_key=True, serialize=False)),
                ('hora_denuncia', models.DateTimeField()),
                ('fecha_denuncia', models.DateField()),
                ('direccion_denuncia', models.CharField(max_length=100)),
                ('direccion_denuncia_1', models.CharField(max_length=225)),
                ('cuadrante_denuncia', models.IntegerField()),
                ('detalle_denuncia', models.TextField()),
                ('visibilidad_camaras_denuncia', models.BooleanField()),
                ('hora_llegada_movil_denuncia', models.DateTimeField()),
                ('labor_realizada_denuncia', models.TextField()),
                ('termino_evento', models.DateTimeField(blank=True, null=True)),
                ('tiempo_total_procedimiento_denuncia', models.IntegerField(blank=True, null=True)),
                ('estado_denuncia', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], max_length=100)),
                ('fecha_creacion_denuncia', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion_denuncia', models.DateTimeField(auto_now=True)),
                ('id_ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Seguridad.ciudadano')),
                ('id_requerimiento', models.ForeignKey(db_column='id_requerimiento_denuncia', on_delete=django.db.models.deletion.PROTECT, to='Seguridad.requerimiento')),
            ],
            options={
                'verbose_name': 'Denuncia',
                'verbose_name_plural': 'Denuncias',
                'db_table': 'Seguridad_denuncia',
            },
        ),
        migrations.CreateModel(
            name='GrupoDenuncia',
            fields=[
                ('id_grupo_denuncia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grupo_denuncia', models.CharField(max_length=100)),
                ('codigo_grupo', models.CharField(max_length=10)),
                ('id_familia_denuncia', models.ForeignKey(db_column='id_familia_denuncia_id', on_delete=django.db.models.deletion.PROTECT, to='Seguridad.familiadenuncia')),
            ],
            options={
                'verbose_name': 'Grupo de Denuncia',
                'verbose_name_plural': 'Grupos de Denuncia',
                'db_table': 'Seguridad_grupodenuncia',
                'unique_together': {('id_familia_denuncia', 'codigo_grupo')},
            },
        ),
        migrations.CreateModel(
            name='SolicitudCiudadano',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_solicitante', models.CharField(max_length=100)),
                ('nombre_solicitante', models.CharField(max_length=225)),
                ('telefono_solicitante', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_solicitante', models.CharField(max_length=225)),
                ('rut_solicitante', models.CharField(max_length=20)),
                ('direccion_solicitante', models.TextField()),
                ('detalle_solicitud', models.TextField()),
                ('estado_solicitud', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], max_length=100)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_ciudadano', models.ForeignKey(db_column='id_ciudadano_id', on_delete=django.db.models.deletion.CASCADE, to='Seguridad.ciudadano')),
            ],
            options={
                'verbose_name': 'Solicitud de Ciudadano',
                'verbose_name_plural': 'Solicitudes de Ciudadanos',
                'db_table': 'Seguridad_solicitud_ciudadano',
            },
        ),
        migrations.CreateModel(
            name='DocumentoSolicitud',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=225)),
                ('tipo_archivo', models.CharField(max_length=50)),
                ('ruta_archivo', models.CharField(max_length=500)),
                ('tamaño_archivo', models.IntegerField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_solicitud', models.ForeignKey(db_column='id_solicitud_id', on_delete=django.db.models.deletion.CASCADE, to='Seguridad.solicitudciudadano')),
            ],
            options={
                'verbose_name': 'Documento de Solicitud',
                'verbose_name_plural': 'Documentos de Solicitud',
                'db_table': 'Seguridad_documento_solicitud',
            },
        ),
        migrations.CreateModel(
            name='SubgrupoDenuncia',
            fields=[
                ('id_subgrupo_denuncia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_subgrupo_denuncia', models.CharField(max_length=100)),
                ('codigo_subgrupo', models.CharField(max_length=10)),
                ('id_grupo_denuncia', models.ForeignKey(db_column='id_grupo_denuncia_id', on_delete=django.db.models.deletion.PROTECT, to='Seguridad.grupodenuncia')),
            ],
            options={
                'verbose_name': 'Subgrupo de Denuncia',
                'verbose_name_plural': 'Subgrupos de Denuncia',
                'db_table': 'Seguridad_subgrupodenuncia',
                'unique_together': {('id_grupo_denuncia', 'codigo_subgrupo')},
            },
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='id_subgrupo_denuncia',
            field=models.ForeignKey(db_column='id_subgrupo_denuncia_id', on_delete=django.db.models.deletion.PROTECT, to='Seguridad.subgrupodenuncia'),
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('patente_vehiculo', models.CharField(max_length=10, unique=True)),
                ('marca_vehiculo', models.CharField(max_length=50)),
                ('modelo_vehiculo', models.CharField(max_length=50)),
                ('codigo_vehiculo', models.CharField(max_length=10)),
                ('estado_vehiculo', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_tipo_vehiculo', models.ForeignKey(db_column='id_tipo_vehiculo_id', on_delete=django.db.models.deletion.PROTECT, to='Seguridad.tiposvehiculos')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'Seguridad_vehiculos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('rut_usuario', models.CharField(max_length=12, unique=True)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('apellido_pat_usuario', models.CharField(max_length=100)),
                ('apellido_mat_usuario', models.CharField(max_length=100)),
                ('correo_electronico_usuario', models.CharField(max_length=254, unique=True)),
                ('telefono_movil_usuario', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('id_rol', models.ForeignKey(db_column='id_rol_id', on_delete=django.db.models.deletion.PROTECT, to='Seguridad.roles')),
                ('id_turno', models.ForeignKey(blank=True, db_column='id_turno_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Seguridad.turnos')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Seguridad_usuario',
            },
        ),
        migrations.CreateModel(
            name='SolicitudTrabajador',
            fields=[
                ('id_solicitud_trabajador', models.AutoField(primary_key=True, serialize=False)),
                ('rol_solicitante', models.CharField(max_length=100)),
                ('nombre_solicitante_trabajador', models.CharField(max_length=225)),
                ('telefono_solicitante_trabajador', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_solicitante_trabajador', models.CharField(max_length=225)),
                ('rut_solicitante_trabajador', models.CharField(max_length=20)),
                ('direccion_solicitante_trabajador', models.TextField()),
                ('detalle_solicitud_trabajador', models.TextField()),
                ('estado_solicitud_trabajador', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], max_length=100)),
                ('fecha_creacion_trabajador', models.DateTimeField(default=django.utils.timezone.now)),
                ('turno_solicitante_trabajador', models.DateField()),
                ('id_usuario', models.ForeignKey(db_column='id_usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Trabajador',
                'verbose_name_plural': 'Solicitudes de Trabajadores',
                'db_table': 'Seguridad_solicitud_trabajador',
            },
        ),
        migrations.CreateModel(
            name='Fiscalizacion',
            fields=[
                ('id_fiscalizacion', models.AutoField(primary_key=True, serialize=False)),
                ('hora_fiscalizacion', models.DateTimeField()),
                ('tipo_fiscalizacion', models.CharField(max_length=100)),
                ('detalle_fiscalizacion', models.TextField()),
                ('nombre_conductor', models.CharField(max_length=225)),
                ('apellido_conductor', models.CharField(max_length=225)),
                ('rut_conductor', models.CharField(max_length=20)),
                ('patente_vehiculo_fiscalizacion', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fiscalización',
                'verbose_name_plural': 'Fiscalizaciones',
                'db_table': 'Seguridad_fiscalizacion',
            },
        ),
        migrations.CreateModel(
            name='DerivacionesDenuncia',
            fields=[
                ('id_derivacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_derivacion', models.CharField(choices=[('emergencia', 'Emergencia'), ('especializada', 'Especializada'), ('seguimiento', 'Seguimiento')], max_length=20)),
                ('hora_derivacion', models.DateTimeField()),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('id_denuncia', models.ForeignKey(db_column='id_denuncia_id', on_delete=django.db.models.deletion.CASCADE, to='Seguridad.denuncia')),
                ('id_servicio', models.ForeignKey(blank=True, db_column='id_servicio_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='Seguridad.serviciosemergencia')),
                ('id_conductor', models.ForeignKey(blank=True, db_column='id_conductor_id', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Derivación de Denuncia',
                'verbose_name_plural': 'Derivaciones de Denuncia',
                'db_table': 'Seguridad_derivacionesdenuncia',
            },
        ),
        migrations.AddField(
            model_name='denuncia',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denuncias_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AsignacionDerivacionEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_derivacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seguridad.derivacionesdenuncia')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seguridad.serviciosemergencia')),
            ],
            options={
                'verbose_name': 'Asignación de Derivación de Emergencia',
                'verbose_name_plural': 'Asignaciones de Derivación de Emergencia',
                'db_table': 'Seguridad_asignacion_derivacion_emergencia',
                'unique_together': {('id_servicio', 'id_derivacion', 'fecha_asignacion')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='requerimiento',
            unique_together={('id_subgrupo_denuncia', 'codigo_requerimiento')},
        ),
        migrations.CreateModel(
            name='MovilesDenuncia',
            fields=[
                ('id_movil_denuncia', models.AutoField(primary_key=True, serialize=False)),
                ('orden_asignacion', models.IntegerField()),
                ('hora_asignacion', models.DateTimeField()),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('id_denuncia', models.ForeignKey(db_column='id_denuncia_id', on_delete=django.db.models.deletion.CASCADE, to='Seguridad.denuncia')),
                ('id_vehiculo', models.ForeignKey(db_column='id_vehiculo_id', on_delete=django.db.models.deletion.PROTECT, to='Seguridad.vehiculos')),
                ('id_conductor', models.ForeignKey(db_column='id_conductor_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Móvil de Denuncia',
                'verbose_name_plural': 'Móviles de Denuncia',
                'db_table': 'Seguridad_movilesdenuncia',
                'unique_together': {('id_denuncia', 'orden_asignacion')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seguridad.vehiculos')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de Vehículo',
                'verbose_name_plural': 'Asignaciones de Vehículo',
                'db_table': 'Seguridad_asignacion_vehiculo',
                'unique_together': {('id_usuario', 'id_vehiculo', 'fecha_asignacion')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('id_radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seguridad.radio')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de Radio',
                'verbose_name_plural': 'Asignaciones de Radio',
                'db_table': 'Seguridad_asignacion_radio',
                'unique_together': {('id_usuario', 'id_radio', 'fecha_asignacion')},
            },
        ),
    ]
