# Generated by Django 5.2.5 on 2025-10-03 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seguridad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
    ]
